Repository atlp-rwanda/script-heroes-frontend, pull requests merged in 2021-02, with the labels that each got.

#31 #174797486 Travel Admins should be able to create Accommodation Facilities
  package.json
  redux/actions/accommodation.js
  redux/actions/authActions.js
  redux/actions/locations.js
  redux/actions/types.js
  redux/reducers/accomodations.js
  redux/reducers/index.js
  redux/reducers/locations.js
  redux/store.js
  src/App.js
  src/App.scss
  src/Views/accommodation.js
  src/components/Login.js
  src/components/Navigation.js
  src/components/accommodation/accommodations.scss
  src/components/accommodation/addAccommodation.js
  src/components/accommodation/editAccommodation.js
  src/tests/components/__snapshots__/loginAuth.test.js.snap
  src/tests/components/profile/View/__snapshots__/index.test.js.snap
  src/tests/index.test.js
  src/tests/views/__snapshots__/login.view.test.js.snap
  src/tests/views/addAccommodation.test.js
  src/tests/views/editAccommodation.test.js
  src/views/Login/Login.js
  src/views/Login/Login.scss
  yarn.lock
Labels: Ready For Review, TTL Review

#32 #175719067 Users should be able to create a travel request
  package.json
  redux/actions/tripRequest.js
  redux/actions/types.js
  redux/reducers/index.js
  redux/reducers/tripRequest.js
  src/App.js
  src/Views/editTravelRequest.js
  src/Views/travelRequest.js
  src/components/Navigation.js
  src/components/requests/adminRequests/AdminRequests.js
  src/components/requests/editTravelRequest.js
  src/components/requests/travelRequest.js
  src/components/requests/travelRequest.scss
  src/tests/__snapshots__/index.test.js.snap
  src/tests/components/__snapshots__/Navigation.test.js.snap
  src/tests/views/__snapshots__/editAccommodation.test.js.snap
  src/utils/axios.js
  yarn.lock
Labels: Open for Suggestions, Ready For Review, WIP

#33 #174797466 Login with Facebook and Google
  src/assets/img/fb_logo.jpg
  src/assets/img/google_logo.png
  src/components/Login.js
  src/components/Login.scss
Labels: Ready For Review
